# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Online Book Portal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3800
        container port: 3307
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'test'
        mysql user: 'dev'
        mysql password: 'test123'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysqlclient
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Run migrations
#      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
